# Generated by Django 4.1.3 on 2022-12-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_category_expense_itembought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembought',
            name='itemLoc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itembought',
            name='itemName',
            field=models.CharField(max_length=255),
        ),
    ]
