# Generated by Django 4.1.3 on 2022-12-24 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_rename_itemdesc_item_desc_rename_itemloc_item_loc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='expensesUnderCategory', to='expense.category'),
        ),
    ]
