# Generated by Django 4.1.3 on 2023-01-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
