# Generated by Django 4.1.3 on 2023-01-09 22:24

from django.db import migrations, models
import expense.models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to=expense.models.UploadFile.user_path_directory),
        ),
    ]
