# Generated by Django 4.1.3 on 2023-01-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0010_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
